collections_config:
  blog:
    path: "src/content/blog"
    output: true
    url: "src/content/blog/[slug]"
  team:
    path: "src/content/team"
    output: true
    url: "src/content/team/[slug]"
paths:
  uploads: /images